//////////////////////////////////////////////////////////////////////////////
// We are creating a driver class for driving the inputs here by using mailbox 
// we will get the randomized inputs from generator  are generated by mailbox 
// by put method and by using transaction class we are getting by get method
// in driver class.
//
/////////////////////////////////////////////////////////////////////////////
`ifndef DRIVER_A_SV
`define DRIVER_A_SV
class driver_a;
  // Mailbox from generator to driver
  mailbox #(transaction) gen2drv_a;
  virtual dual_port_vif  dp_vif;

  // Constructor: keep parameter order consistent with the member above.
  function new(mailbox#(transaction) gen2drv_a, virtual dual_port_vif dp_vif);
    this.gen2drv_a = gen2drv_a;
    this.dp_vif    = dp_vif;
  endfunction

  // Optional: initial defaults (can be moved to run())
  task init_defaults();
    // Drive safe defaults before starting
    dp_vif.i_en_a   <= 1'b0;
    dp_vif.i_we_a   <= 1'b0;
    dp_vif.i_addr_a <= '0;
    dp_vif.i_din_a  <= '0;
  endtask

  task run();
    transaction t;

    // Initialize outputs once
    init_defaults();

    forever begin
      // Block until we receive the next item
      gen2drv_a.get(t);
      dp_vif.i_en_a   <= t.i_en_a;
      dp_vif.i_we_a   <= t.i_we_a;
      dp_vif.i_din_a  <= t.i_din_a;
      dp_vif.i_addr_a <= t.i_addr_a;
      @(negedge dp_vif.i_clk_a);
    end
  endtask
endclass
`endif
